   ( English:'English';
     Native:'American English';
     LangFile:'english.lang';
     DicFile:'english.dic';
     FlagID:'us';
     Letters:'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z';
     LetterCount:'9,2,2,4,12,2,3,2,9,1,1,4,2,6,8,2,1,6,4,6,4,2,2,1,2,1';
     LetterValue:'1,3,3,2,1,4,2,4,1,8,5,1,3,1,1,3,10,1,1,1,1,4,4,8,4,10';
     NumberOfJokers:2;
     ReadingDirection:rdLeftToRight;
     ExcludedCat:'1'; //page 29, VI.A.
     RulesValid:true;
     NumberOfLetters:7;
     NumberOfRandoms:0;
     TimeControl:2;
     TimeControlEnd:false;
     TimeControlBuy:true; //page 26, V.F.3.
     TimePerGame:'0:50:00'; //page 26, V.F.2.
     PenaltyValue:10; //page 26, V.F.2.
     PenaltyCount:10; //page 26, V.F.3.
     GameLostByTime:true; //page 26, V.F.3.
     WordCheckMode:2;
     ChallengePenalty:0;  //doubtful, but in fact in the rules nothing is written about that issue
     ChallengeTime:20; //page 20, IV.I.1.
     JokerExchange:false;
     ChangeIsPass:true; //page 25, V.C.2
     CambioSecco:false;
     SubstractLetters:true; //page 25, V.F.1. (adapted to the current features of Scrabble3D)
     AddLetters:true; //page 25, V.F.1. (adapted to the current features of Scrabble3D)
     JokerPenalty:0;
     NumberOfPasses:3; //page 25, V.C.2
     LimitExchange:7; //page 16, IV.E.2.a.
     EndBonus:0;
     ScrabbleBonus:50)

{References:
http://www.scrabbleplayers.org/wiki/images/9/95/Rules-20120616.pdf (NASPA, June 27, 2012) 
http://www.scrabbleplayers.org/w/Welcome_to_NASPAWiki
http://www.scrabbleplayers.org/w/Rules
-
Current state of implementation in this *.inc file: 2012-08-10 }
