( English:'Catalan';
  Native:'Català';
  LangFile:'catalan.lang';
  DicFile:'catalan.dic';
  FlagID:'Catalonia';
  Letters:'A,B,C,Ç,D,E,F,G,H,I,J,L,1,M,N,2,O,P,3,R,S,T,U,V,X,Z';
  LetterCount:'12,2,3,1,3,13,1,2,1,8,1,4,1,3,6,1,5,2,1,8,8,5,4,1,1,1';
  LetterValue:'1,3,2,10,2,1,4,3,8,1,8,1,10,2,1,10,1,3,8,1,1,1,1,4,10,8';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:'';
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true; //page 6, point 7
  TimePerGame:'1:00:00'; //chosen arbitrarily, because the time may differ for every tournament
  PenaltyValue:10; //page 6, point 7
  PenaltyCount:10; //page 6, point 7
  GameLostByTime:true; //page 6, point 7
  WordCheckMode:2;
  ChallengePenalty:0; //nothing is explicitly mentioned about any challenge penalty; see page 6, point 6.
  ChallengeTime:30; //chosen arbitrarily
  JokerExchange:false;
  ChangeIsPass:false; //page 4, point 4 b)
  CambioSecco:true; //since the "Senyors" rule is not possible in Scrabble3D, the Italian Cambio secco has been chosen instead
  SubstractLetters:true;
  AddLetters:true;
  JokerPenalty:0;
  NumberOfPasses:3; //page 4, point 4 b)
  LimitExchange:7; //page 4, point 3
  EndBonus:0;
  ScrabbleBonus:50)

  {References:  
  http://www.fiscrabble.cat/wp-content/uploads/2011/07/Reglament-de-joc.pdf (July 2011)
  http://www.fiscrabble.cat/
  http://www.fiscrabble.cat/reglaments-oficials/reglament-de-joc/
  http://17085.homepagemodules.de/t1820f327-quot-Senyors-quot-the-Catalan-variant-of-Italian-quot-Cambio-Secco-quot.html
  http://www.olissip.com/Reglament-general.pdf (2007; not official)
  -
  Current state of implementation in this *.inc file: 2012-08-10}
