( English:'Dutch';
  Native:'Nederlands';
  LangFile:'';
  DicFile:'hollands.dic';
  FlagID:'nl';
  Letters:'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z';
  LetterCount:'6,2,2,5,18,2,3,2,4,2,3,3,3,10,6,2,1,5,5,5,3,2,2,1,1,2';
  LetterValue:'1,3,5,2,1,4,3,4,1,4,3,3,3,1,1,3,10,2,2,2,4,4,5,8,8,4';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:''; 
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'0:50:00'; //page 22, 5.3.5
  PenaltyValue:10; //page 21, 5.3.2
  PenaltyCount:10; //page 21, 5.3.3
  GameLostByTime:true; //page 21, 5.3.3
  WordCheckMode:2;
  ChallengePenalty:5; //one of the possibilities according to WESPA v2, see page 17, 3.10.15 and page 18, 3.10.15 (d)
  ChallengeTime:20; //chosen arbitrarily, not enshrined in the rules, see page 15, 3.10.3
  JokerExchange:false;
  ChangeIsPass:true; //page 21, 5.2
  CambioSecco:false;
  SubstractLetters:true; //page 21, 5.1.4
  AddLetters:true; //page 21, 5.1.4
  JokerPenalty:0;
  NumberOfPasses:3; //page 21, 5.2
  LimitExchange:7; //page 11, 3.2.1
  EndBonus:0;
  ScrabbleBonus:50)

  {Comment:
  There are two official Scrabble Federations for Dutch Scrabble: one in the Netherlands and one in Belgium, 
  and therefore there are official rules for Scrabble tournaments in Dutch language indeed, but those
  rules have not been published on internet and they cannot be downloaded either:
  http://www.scrabblebond.nl/www/inh.htm
  http://www.ntsv.net/
  Whoever wants to read those rules has to buy them from one of the Scrabble Federations for Dutch Scrabble. 
  That's the reason why for the present and temporarily the English WESPA rules have arbitrarily 
  been chosen instead of the Dutch rules.  
  -
  References:
  http://www.wespa.org/rules/RulesV2nov11.pdf (WESPA 2.0 from 2010-11-17)
  Current state of implementation in this *.inc file: 2012-08-10 } 
  
  
  
