( English:'Finnish';
  Native:'Suomi';
  LangFile:'finnish.lang';
  DicFile:'suomi.dic';
  FlagID:'fi';
  Letters:'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,R,S,T,U,V,Y,Ä,Ö';
  LetterCount:'10,1,1,1,8,1,1,2,10,2,5,5,3,9,5,2,2,7,9,4,2,2,5,1';
  LetterValue:'1,8,10,7,1,8,8,4,1,4,2,2,3,1,2,4,4,1,1,3,4,4,2,7';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:'';
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'1:00:00';
  PenaltyValue:10;
  PenaltyCount:5;
  GameLostByTime:true;
  WordCheckMode:2;
  ChallengePenalty:10;
  ChallengeTime:20; //nothing about that issue is found in the rules, that's why this value has been chosen arbitrarily
  JokerExchange:false;
  ChangeIsPass:true;
  CambioSecco:false;
  SubstractLetters:true;
  AddLetters:true;
  JokerPenalty:0;
  NumberOfPasses:3;
  LimitExchange:7;
  EndBonus:0;
  ScrabbleBonus:50)

  {Comment:
  It is understood that there are no official tournament rules for Scrabble in Finnish language, because there is no
  Finnish Scrabble Federation. That's why Swedish tournament rules have arbitrarily been chosen for Scrabble games in 
  Finnish language. The following reasons have been taken into consideration: Finland is a neighbouring country of Sweden, 
  Finnish and Swedish are the official languages of Finland, Swedish is spoken in some coastal areas in the west and 
  south and in the autonomous region of Åland, many Finns are living in Sweden. That's why Finns might have more 
  affinity towards Sweden and the Swedish rules than towards the UK or the USA and the WESPA or NASPA rules.
  -
  References:
  http://www.scrabbleforbundet.se/index.php?option=content&task=view&id=16&Itemid=39
  http://www.scrabbleforbundet.se
  The booklet with the game rules which is included when you buy the Swedish edition of the board game.
  Comment:
  Where nothing is written about some issue in the tournament rules, the settings refer to the
  booklet with the game rules which is included when you buy the Swedish edition of the board game.
  -
  Current state of implementation in this *.inc file: 2012-08-10 }
  
  
