( English:'Hebrew';
  Native:'עברית';
  LangFile:'';
  DicFile:'hebrew.dic';
  FlagID:'il';
  Letters:'א,ב,ג,ד,ה,ו,ז,ח,ט,י,כ,ל,מ,נ,ס,ע,פ,צ,ק,ר,ש,ת';
  LetterCount:'6,4,2,4,8,12,1,3,1,10,2,6,6,4,1,2,3,1,3,8,6,9';
  LetterValue:'2,3,5,3,1,1,8,4,8,1,5,2,2,3,8,5,4,8,4,1,2,1';
  NumberOfJokers:2;
  ReadingDirection:rdRightToLeft;
  ExcludedCat:''; 
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'0:50:00'; //page 22, 5.3.5
  PenaltyValue:10; //page 21, 5.3.2
  PenaltyCount:10; //page 21, 5.3.3
  GameLostByTime:true; //page 21, 5.3.3
  WordCheckMode:2;
  ChallengePenalty:5; //one of the possibilities according to WESPA v2, see page 17, 3.10.15 and page 18, 3.10.15 (d)
  ChallengeTime:20; //chosen arbitrarily, not enshrined in the rules, see page 15, 3.10.3
  JokerExchange:false;
  ChangeIsPass:true; //page 21, 5.2
  CambioSecco:false;
  SubstractLetters:true; //page 21, 5.1.4
  AddLetters:true; //page 21, 5.1.4
  JokerPenalty:0;
  NumberOfPasses:3; //page 21, 5.2
  LimitExchange:7; //page 11, 3.2.1
  EndBonus:0;
  ScrabbleBonus:50)

{Comment:
It is understood that there are no official tournament rules for Scrabble in Hebrew language.
In Israel all official tournaments seem to be held in English language only. That's the reason 
why these Scrabble3D settings refer to the English WESPA rules even for games in Hebrew language. 
-
References:
http://www.scrabble.org.il/rulesregulations.htm
http://www.scrabble.org.il/
http://www.wespa.org/rules/RulesV2nov11.pdf (WESPA 2.0 from 2010-11-17)
http://www.wespa.org
-
Current state of implementation in this *.inc file: 2012-08-10}
