( English:'Italian';
  Native:'Italiano';
  LangFile:'italian.lang';
  DicFile:'italiano.dic';
  FlagID:'it';
  Letters:'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z';
  LetterCount:'14,3,6,3,11,3,2,2,12,0,0,5,5,5,15,3,1,6,6,6,5,3,0,0,0,2';
  LetterValue:'1,5,2,5,1,5,8,8,1,0,0,3,3,3,1,5,10,2,2,2,3,5,0,0,0,8';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:'1';
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true; 
  TimePerGame:'0:50:00'; 
  PenaltyValue:30; //page 11, point 37. Different penalties are not possible in Scrabble3D. But in Scrabble3D, however, the result will be exactly the same.
  PenaltyCount:1; 
  GameLostByTime:true; 
  WordCheckMode:2; 
  ChallengePenalty:10; //page 10, point 30 not being a feature in Scrabble3D, a value of 10 points has been chosen arbitrarily instead
  ChallengeTime:20; //page 10, point 31
  JokerExchange:false;
  ChangeIsPass:true; //page 11, point 39 b) 
  CambioSecco:true; //page 11, point 35
  SubstractLetters:true; //page 12, point 40
  AddLetters:false; //page 12, point 40 (not explicitly mentioned, but derived indirectly)
  JokerPenalty:7; //page 12, point 40
  NumberOfPasses:3; //page 11, point 39 b)
  LimitExchange:3; //page 10, point 34
  EndBonus:0;
  ScrabbleBonus:50)
  
  {References:
  http://www.scrabbleitalia.com/regnaz.pdf (2012-09-13)
  http://www.scrabbleitalia.com 
  -
  Current state of implementation in this *.inc file: 2012-09-13 }
  
