( English:'Latin';
  Native:'Lingua Latina';
  LangFile:'';
  DicFile:'';
  FlagID:'latin';
  Letters:'A,B,C,D,E,F,G,H,I,K,L,M,N,O,P,Q,R,S,T,U,V,X,Y,Z';
  LetterCount:'9,2,4,3,11,1,1,1,11,0,2,5,6,5,2,1,9,8,7,7,2,1,0,0';
  LetterValue:'1,5,2,3,1,6,6,10,1,0,4,2,1,2,4,10,1,1,1,1,5,6,0,0';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:'';
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'1:00:00'; //in order to alleviate this issue, a longer time has been chosen arbitrarily, because nowadays NOBODY has Latin as native language
  PenaltyValue:10;
  PenaltyCount:10;
  GameLostByTime:true;
  WordCheckMode:2;
  ChallengePenalty:10; //chosen arbitrarily
  ChallengeTime:60; //in order to alleviate this issue, a longer time has been chosen arbitrarily, because nowadays NOBODY has Latin as native language
  JokerExchange:false;
  ChangeIsPass:false; //in order to alleviate this issue, this setting has been chosen arbitrarily, because nowadays NOBODY has Latin as native language
  CambioSecco:false; //CS has not been chosen, because this Italian rule is rather unknown all over the world
  SubstractLetters:true;
  AddLetters:true;
  JokerPenalty:0;
  NumberOfPasses:3;
  LimitExchange:7;
  EndBonus:0;
  ScrabbleBonus:50)

  {Comment:
  It is understood that there are no official tournament rules for Scrabble in Latin language, because there 
  is no Scrabble Federation for Latin Scrabble. That's why the English WESPA tournament rules have arbitrarily 
  been chosen for Scrabble games in Latin language.   
  The following reason has been taken into consideration: The WESPA rules might be best known all over the world.
  -
  References:
  http://www.wespa.org/rules/RulesV2nov11.pdf
  http://www.wespa.org/index.shtml
  -
  Current state of implementation in this *.inc file: 2012-08-10}
