(English:'Romanian';
 Native:'Română';
 LangFile:'';
 DicFile:'romana.dic';
 FlagID:'ro';
 Letters:'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z';
 LetterCount:'11,2,5,4,9,2,2,1,10,1,0,4,3,6,5,4,0,7,5,7,6,2,0,1,0,1';
 LetterValue:'1,9,1,2,1,8,9,10,1,10,0,1,4,1,1,2,0,1,1,1,1,8,0,10,0,10';
 NumberOfJokers:2;
 ReadingDirection:rdLeftToRight;
 ExcludedCat:'';
 RulesValid:true;
 NumberOfLetters:7;
 NumberOfRandoms:0;
 TimeControl:2;
 TimeControlEnd:true;
 TimeControlBuy:false;
 TimePerGame:'0:50:00';
 PenaltyValue:1; //this value ought to be zero, but zero is prohibited in the program
 PenaltyCount:1; //this value ought to be zero, but zero is prohibited in the program
 GameLostByTime:true;
 WordCheckMode:2;
 ChallengePenalty:10; //point 5.10.15. and http://17085.homepagemodules.de/t1239f330-Assistant-Which-default-settings-do-you-wish-for-Romanian-games.html#msg9872524
 ChallengeTime:20; //chosen arbitrarily 
 JokerExchange:false;
 ChangeIsPass:true;
 CambioSecco:false;
 SubstractLetters:true;
 AddLetters:true;
 JokerPenalty:0;
 NumberOfPasses:3;
 LimitExchange:7;
 EndBonus:0;
 ScrabbleBonus:50)

  {References:
  http://www.scrabblero.ro/reg/reg-libera2011.doc 
  http://www.scrabblero.ro/
  http://www.scrabblero.ro/regulamente.htm
  http://17085.homepagemodules.de/t1239f330-Assistant-Which-default-settings-do-you-wish-for-Romanian-games.html
  -
  Current state of implementation in this *.inc file: 2012-08-10}
  
