( English:'Russian';
  Native:'Русский';
  LangFile:'';
  DicFile:'russian.dic';
  FlagID:'ru';
  Letters:'А,Б,В,Г,Д,Е,Ё,Ж,З,И,Й,К,Л,М,Н,О,П,Р,С,Т,У,Ф,Х,Ц,Ч,Ш,Щ,Ъ,Ы,Ь,Э,Ю,Я';
  LetterCount:'8,2,4,2,4,8,1,1,2,5,1,4,4,3,5,10,4,5,5,5,4,1,1,1,1,1,1,1,2,2,1,1,2';
  LetterValue:'1,3,1,3,2,1,3,5,5,1,4,2,2,2,1,1,2,1,1,1,2,10,5,5,5,8,10,10,4,3,8,8,3';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:''; 
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'0:50:00'; //page 22, 5.3.5
  PenaltyValue:10; //page 21, 5.3.2
  PenaltyCount:10; //page 21, 5.3.3
  GameLostByTime:true; //page 21, 5.3.3
  WordCheckMode:2;
  ChallengePenalty:5; //one of the possibilities according to WESPA v2, see page 17, 3.10.15 and page 18, 3.10.15 (d)
  ChallengeTime:20; //chosen arbitrarily, not enshrined in the rules, see page 15, 3.10.3
  JokerExchange:false;
  ChangeIsPass:true; //page 21, 5.2
  CambioSecco:false;
  SubstractLetters:true; //page 21, 5.1.4
  AddLetters:true; //page 21, 5.1.4
  JokerPenalty:0;
  NumberOfPasses:3; //page 21, 5.2
  LimitExchange:7; //page 11, 3.2.1
  EndBonus:0;
  ScrabbleBonus:50)

  {Comment:
  It is understood that there are no official tournament rules for Scrabble in Russian language, because there 
  is no Russian Scrabble Federation. That's why the English WESPA tournament rules have arbitrarily been chosen  
  for Scrabble games in Russian language. 
  -
  References:
  http://www.wespa.org/rules/RulesV2nov11.pdf
  -
  Current state of implementation in this *.inc file: 2012-08-10}
  
