( English:'Slovak';
  Native:'Slovenčina';
  LangFile:'slovak.lang';
  DicFile:'slovak.dic';
  FlagID:'sk';
  Letters:'A,Á,Ä,B,C,Č,D,Ď,E,É,F,G,H,I,Í,J,K,L,Ľ,Ĺ,M,N,Ň,O,Ô,Ó,Ö,P,Q,R,Ŕ,S,Š,T,Ť,U,Ú,Ü,V,W,X,Y,Ý,Z,Ž';
  LetterCount:'9,1,1,2,1,1,3,1,8,1,1,1,1,5,1,2,3,3,1,1,4,5,1,9,1,1,0,3,0,4,1,4,1,4,1,2,1,0,4,0,1,1,1,1,1';
  LetterValue:'1,4,10,4,4,5,2,8,1,7,8,8,4,1,5,3,2,2,7,10,2,1,8,1,8,10,0,2,0,1,10,1,5,1,7,3,7,0,1,0,10,4,5,4,5';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:'';
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:true;
  TimeControlBuy:false;
  TimePerGame:'0:44:00';
  PenaltyValue:1; //this value ought to be zero, but zero is prohibited in the program
  PenaltyCount:1; //this value ought to be zero, but zero is prohibited in the program
  GameLostByTime:false;  
  WordCheckMode:2;
  ChallengePenalty:10; //"unrighteous challenge penalty: 1st time (counted per player) > 10 points, all next > challenger will miss a turn" is not possible in Scrabble3D
  ChallengeTime:20; //chosen arbitrarily
  JokerExchange:false;
  ChangeIsPass:true;
  CambioSecco:false;
  SubstractLetters:true;
  AddLetters:true;
  JokerPenalty:0;
  NumberOfPasses:3;
  LimitExchange:7;
  EndBonus:0;
  ScrabbleBonus:50)

  {References:  
  http://www.hramescrabble.sk/
  Discussion on http://17085.homepagemodules.de/t1494f349-Official-Slovakian-Scrabble-Rules.html
  -
  Current state of implementation in this *.inc file: 2012-08-10}
