( English:'Swedish';
  Native:'Svenska';
  LangFile:'swedish.lang';
  DicFile:'svenska.dic';
  FlagID:'se';
  Letters:'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,Ä,Å,Æ,Ö,Ü';
  LetterCount:'8,2,1,5,7,2,3,2,5,1,3,5,3,6,5,2,0,8,8,8,3,2,0,1,1,1,2,2,0,2,0';
  LetterValue:'1,4,8,1,1,3,2,2,1,7,2,1,2,1,2,4,0,1,1,1,4,3,0,8,7,10,3,4,0,4,0';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:'1';
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'1:00:00';
  PenaltyValue:10;
  PenaltyCount:5;
  GameLostByTime:true;
  WordCheckMode:2;
  ChallengePenalty:10;
  ChallengeTime:20; //nothing about that issue is found in the rules, that's why this value has been chosen arbitrarily
  JokerExchange:false;
  ChangeIsPass:true;
  CambioSecco:false;
  SubstractLetters:true;
  AddLetters:true;
  JokerPenalty:0;
  NumberOfPasses:3;
  LimitExchange:7;
  EndBonus:0;
  ScrabbleBonus:50)

  {References:
  http://www.scrabbleforbundet.se/index.php?option=content&task=view&id=16&Itemid=39
  http://www.scrabbleforbundet.se
  The booklet with the game rules which is included when you buy the Swedish edition of the board game.
  Comment:
  Where nothing is written about some issue in the tournament rules, the settings refer to the
  booklet with the game rules which is included when you buy the Swedish edition of the board game.
  -
  Current state of implementation in this *.inc file: 2012-08-10 } 
