( English:'Scottish Gaelic';
  Native:'Gàidhlig';
  LangFile:'scottishgaelic.lang';
  DicFile:'scottishgaelic.dic';
  FlagID:'scotland';
  Letters:'A,À,B,Ḃ,C,Ċ,D,Ḋ,E,È,F,Ḟ,G,Ġ,I,Ì,L,Ḻ,M,Ṁ,N,Ṉ,O,Ò,P,Ṗ,R,Ṟ,S,Ṡ,T,Ṫ,U,Ù';
  LetterCount:'15,1,2,1,3,3,3,3,10,1,1,1,3,1,11,1,3,1,2,1,4,1,4,1,1,1,4,1,4,1,3,3,2,1';
  LetterValue:'1,5,3,2,3,2,2,2,1,6,5,5,3,5,1,6,2,8,3,5,1,4,1,6,6,1,1,8,1,1,3,3,2,6';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:''; 
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'0:50:00'; //page 22, 5.3.5
  PenaltyValue:10; //page 21, 5.3.2
  PenaltyCount:10; //page 21, 5.3.3
  GameLostByTime:true; //page 21, 5.3.3
  WordCheckMode:2;
  ChallengePenalty:5; //one of the possibilities according to WESPA v2, see page 17, 3.10.15 and page 18, 3.10.15 (d)
  ChallengeTime:20; //chosen arbitrarily, not enshrined in the rules, see page 15, 3.10.3
  JokerExchange:false;
  ChangeIsPass:true; //page 21, 5.2
  CambioSecco:false;
  SubstractLetters:true; //page 21, 5.1.4
  AddLetters:true; //page 21, 5.1.4
  JokerPenalty:0;
  NumberOfPasses:3; //page 21, 5.2
  LimitExchange:7; //page 11, 3.2.1
  EndBonus:0;
  ScrabbleBonus:50)

  {References:
  http://www.absp.org.uk/index.shtml 
  http://17085.homepagemodules.de/t1212f328-Assistant-Which-default-settings-do-you-wish-for-Scottish-Gaelic.html
  http://www.wespa.org/rules/RulesV2nov11.pdf (WESPA 2.0 rules from 2010-11-17 have been valid in the UK since 2012-01-01)
  -
  Current state of implementation in this *.inc file: 2012-08-10}
  
  
