( English:'Turkish';
  Native: 'Türkçe';
  LangFile:'';
  DicFile:'turkish.dic';
  FlagID:'tr';
  Letters:'A,B,C,Ç,D,E,F,G,Ğ,H,I,İ,J,K,L,M,N,O,Ö,P,R,S,Ş,T,U,Ü,V,Y,Z';
  LetterCount:'12,2,2,2,2,8,1,1,1,1,4,7,1,7,7,4,5,3,1,1,6,3,2,5,3,2,1,2,2';
  LetterValue:'1,3,4,4,3,1,7,5,8,5,2,1,10,1,1,2,1,2,7,5,1,2,4,1,2,3,7,3,4';
  NumberOfJokers:2;
  ReadingDirection:rdLeftToRight;
  ExcludedCat:''; 
  RulesValid:true;
  NumberOfLetters:7;
  NumberOfRandoms:0;
  TimeControl:2;
  TimeControlEnd:false;
  TimeControlBuy:true;
  TimePerGame:'0:50:00'; //page 22, 5.3.5
  PenaltyValue:10; //page 21, 5.3.2
  PenaltyCount:10; //page 21, 5.3.3
  GameLostByTime:true; //page 21, 5.3.3
  WordCheckMode:2;
  ChallengePenalty:5; //one of the possibilities according to WESPA v2, see page 17, 3.10.15 and page 18, 3.10.15 (d)
  ChallengeTime:20; //chosen arbitrarily, not enshrined in the rules, see page 15, 3.10.3
  JokerExchange:false;
  ChangeIsPass:true; //page 21, 5.2
  CambioSecco:false;
  SubstractLetters:true; //page 21, 5.1.4
  AddLetters:true; //page 21, 5.1.4
  JokerPenalty:0;
  NumberOfPasses:3; //page 21, 5.2
  LimitExchange:7; //page 11, 3.2.1
  EndBonus:0;
  ScrabbleBonus:50)

{References:
 based on rules for British English
Current state of implementation in this *.inc file: 2014-02-27}
